<?php

return array(
  'quickfile_account' => array(
    'group_name' => 'Quickfile Settings',
    'group' => 'quickfile',
    'name' => 'quickfile_account',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Quickfile account',
    'description' =>  'The Quickfile account number.',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'quickfile_apikey' => array(
    'group_name' => 'Quickfile Settings',
    'group' => 'quickfile',
    'name' => 'quickfile_apikey',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Quickfile API Key',
    'description' => 'A static key generated for your account to authenticate your access to the API. This can be found in your Quickfile account settings area.',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'quickfile_application' => array(
    'group_name' => 'Quickfile Settings',
    'group' => 'quickfile',
    'name' => 'quickfile_application',
    'type' => 'Text',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Quickfile application number',
    'description' => 'Each Quickfile application must have an ApplicationID. You can obtain this by registering your application in Quickfile',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
    'quickfile_default_revenue_account' => array(
    'group_name' => 'Quickfile Settings',
    'group' => 'quickfile',
    'name' => 'quickfile_default_revenue_account',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 200,
    'title' => 'Quickfile Default Revenue Account',
    'description' => 'Account to code contributions to',
    'help_text' => 'For more complex rules you will need to add a custom extension',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
 );
